version: 2
updates:
  - package-ecosystem: "bundle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Competitive-Cyber-Clubs/admins"
    commit-message:
      prefix: "bundle Update"
    reviewers:
      - "Competitive-Cyber-Clubs/admins"